spring:
    rabbitmq:
      host: 47.104.128.12
      port: 5672
      virtual-host: tulingVip
      username: guest
      password: guest
      connection-timeout: 10000
      template:
        mandatory: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ms-provider-order-8002
  client:
    service-url:
      defaultZone: http://www.eureka9000.com:9000/eureka/
#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

